apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://helm.mini.dev/argo-cd
    chart: argocd
    targetRevision: 10.2.0
    helm:
      values: |
        argo-cd:
          global:
            domain: argocd.thenoodledragonlair.com
          configs:
            params:
              server.insecure: true
            cm:
              oidc.tls.insecure.skip.verify: true
              oidc.config: |
                name: Keycloak
                issuer: https://keycloak.thenoodledragonlair.com/realms/standard-realm
                clientID: argocd
                clientSecret: $argocd-oidc-secret:clientSecret
                requestedScopes: [openid, profile, email, groups]
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
