apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://quay.io/cilium/charts/cilium
    chart: cilium
    targetRevision: 1.19.4
    helm:
      valuesObject:
        k8sServiceHost: 127.0.0.1
        k8sServicePort: 8443
        operator:
          replicas: 1
        kubeProxyReplacement: true
        ingressController:
          enabled: true
        hubble:
          relay:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
