apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5" # Needed to get CRDs deployed
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true # Needed to get CRDs deployed
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: eck-operator
    targetRevision: 3.3.2
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-cluster
  namespace: elastic
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true # CRD is installed by eck-controller in syncwave -5
spec:
  version: 9.3.0
  nodeSets:
    - name: default
      count: 1
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true # CRD is installed by eck-controller in syncwave -5
spec:
  version: 9.2.1
  count: 1
  elasticsearchRef:
    name: elastic-cluster
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: elastic-agent
    targetRevision: 9.3.3
    helm:
      # I should update this to internal http?
      values: |
        outputs:
          default:
            type: ESPlainAuthAPI
            url: https://elastic-cluster-es-http.elastic.svc.cluster.local:9200
            api_key: yuPo7p0BnX8ErKTLP4Et:Jqh7lKx0BPHUvlYFI-eMHg
            ssl:
              certificateAuthorities:
                - /usr/share/elastic-agent/certs/ca.crt
        system:
          enabled: true
        kubernetes:
          enabled: true
        fleet:
          enabled: false
        agent:
          presets:
            perNode:
              extraVolumeMounts:
                - name: elastic-ca
                  mountPath: /usr/share/elastic-agent/certs/
                  readOnly: true
              extraVolumes:
                - name: elastic-ca
                  secret:
                    secretName: elastic-cluster-es-remote-ca
            clusterWide:
              extraVolumeMounts:
                - name: elastic-ca
                  mountPath: /usr/share/elastic-agent/certs/
                  readOnly: true
              extraVolumes:
                - name: elastic-ca
                  secret:
                    secretName: elastic-cluster-es-remote-ca
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
