apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: agents
  namespace: elastic
spec:
  endpointSelector:
    matchLabels:
      common.k8s.elastic.co/type: agent
  egress:
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "8443"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            elasticsearch.k8s.elastic.co/cluster-name: elastic-cluster
      toPorts:
        - ports:
            - port: "9200"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: kube-state-metrics
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: elastic-cluster
  namespace: elastic
spec:
  endpointSelector:
    matchLabels:
      elasticsearch.k8s.elastic.co/cluster-name: elastic-cluster
  ingress:
    - fromEndpoints:
        - matchLabels:
            common.k8s.elastic.co/type: agent
      toPorts:
        - ports:
            - port: "9200"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            common.k8s.elastic.co/type: kibana
      toPorts:
        - ports:
            - port: "9200"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: elastic-operator
  namespace: elastic
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: elastic-operator
  egress:
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "8443"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: kube-state-metrics
  namespace: elastic
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  egress:
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "8443"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: kibana
  namespace: elastic
spec:
  endpointSelector:
    matchLabels:
      common.k8s.elastic.co/type: kibana
  egress:
    - toFQDNs:
        - matchName: "artifacts.security.elastic.co"
        - matchName: "epr.elastic.co"
        - matchName: "telemetry.elastic.co"
    - toEndpoints:
        - matchLabels:
            elasticsearch.k8s.elastic.co/cluster-name: elastic-cluster
      toPorts:
        - ports:
            - port: "9200"
              protocol: TCP
