apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: eck-operator
    targetRevision: 3.3.2
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-cluster
  namespace: elastic
spec:
  version: 9.3.0
  nodeSets:
    - name: default
      count: 1
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic
spec:
  version: 9.2.1
  count: 1
  elasticsearchRef:
    name: elastic-cluster
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: elastic-agent
    targetRevision: 9.3.3
    helm:
      values: |
        agent:
          outputs:
            default:
              type: ESPlainAuthAPI
              url: http://elastic-cluster-es-http.elastic.svc.cluster.local:9200
              api_key: "EOO66p0BnX8ErKTLPIGI:Ey52qvp8PTxKUKh5-XNW9Q
              # Optional: Disable SSL verification in dev
              ssl:
                verification_mode: none
        system:
          enabled: true
        kubernetes:
          enabled: true
        # Disable Fleet to use standalone mode
        fleet:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
