apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: eck-operator
    targetRevision: 3.3.2
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: example-cluster
spec:
  version: 8.11.0
  nodeSets:
    - name: default
      count: 1
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: example-kibana
spec:
  version: 8.11.0
  elasticsearchRef:
    name: example-cluster
