# apiVersion: "cilium.io/v2"
# kind: CiliumClusterwideNetworkPolicy
# metadata:
#   name: keycloak-ingress
# spec:
#   endpointSelector:
#     matchExpressions:
#       - key: reserved:ingress
#         operator: Exists
#   egress:
#     - toEndpoints:
#         - matchLabels:
#             k8s:io.kubernetes.pod.namespace: keycloak
#             app.kubernetes.io/name: argocd-server
