apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: trivy-egress-world
  namespace: trivy
spec:
  endpointSelector: {}
  egress:
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: trivy-operator
  namespace: trivy
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: trivy-operator
  egress:
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "8443"
              protocol: TCP
