apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: dhi.io
    chart: trivy-operator-chart
    targetRevision: 0.33.1
    helm:
      values: |
        image:
          pullSecrets:
            - name: helm-pull-secret
        trivy:
          pullSecrets:
            - name: helm-pull-secret
        nodeCollector:
          pullSecrets:
            - name: helm-pull-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: trivy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
